const words = [
    "aback",
    "abacli",
    "abacot",
    "abacterial",
    "abactinal",
    "abactinally",
    "abaction",
    "abactor",
    "abaculi",
    "abaculus",
    "abacus",
    "abacuses",
    "abada",
    "abaddon",
    "manic",
    "abadejo",
    "abadengo",
    "abadia",
    "abadite",
    "abaff",
    "abaft",
    "abay",
    "abayah",
    "point",
    "pointy",
    "abaisance",
    "abaised",
    "abaiser",
    "abaisse",
    "abaissed",
    "abaka",
];

module.exports = { words };
